name: Convert YouTube to M4A

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL'
        required: true

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install --upgrade yt-dlp
      - name: Run
        run: python download.py "${{ github.event.inputs.video_url }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          files: output/*.m4a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
